name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      
      - uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 12

      - name: ci
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Publish to Visual Studio Marketplace
        if: ${{ steps.release.outputs.release_created }}
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to Open VSX Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
